// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_test_increment = "CgkI18-M-9keEAIQFg"; // <GPGSID>
        public const string achievement_test_instant = "CgkI18-M-9keEAIQFw"; // <GPGSID>
        public const string achievement_gamer = "CgkI18-M-9keEAIQCw"; // <GPGSID>
        public const string achievement_wardrobe_beginner = "CgkI18-M-9keEAIQEQ"; // <GPGSID>
        public const string event_floor_climbed = "CgkI18-M-9keEAIQAg"; // <GPGSID>
        public const string achievement_its_raining = "CgkI18-M-9keEAIQDQ"; // <GPGSID>
        public const string achievement_wardrobe_advanced = "CgkI18-M-9keEAIQEg"; // <GPGSID>
        public const string leaderboard_top_score = "CgkI18-M-9keEAIQAA"; // <GPGSID>
        public const string achievement_coin_collector = "CgkI18-M-9keEAIQEw"; // <GPGSID>
        public const string achievement_good_score = "CgkI18-M-9keEAIQDg"; // <GPGSID>
        public const string achievement_electrician = "CgkI18-M-9keEAIQDA"; // <GPGSID>
        public const string achievement_awesome_score = "CgkI18-M-9keEAIQEA"; // <GPGSID>
        public const string achievement_regifter = "CgkI18-M-9keEAIQFQ"; // <GPGSID>
        public const string achievement_vidiot = "CgkI18-M-9keEAIQCg"; // <GPGSID>
        public const string achievement_hundo_club = "CgkI18-M-9keEAIQAw"; // <GPGSID>
        public const string achievement_im_floored = "CgkI18-M-9keEAIQCA"; // <GPGSID>
        public const string achievement_great_score = "CgkI18-M-9keEAIQDw"; // <GPGSID>
        public const string achievement_coin_explosion = "CgkI18-M-9keEAIQFA"; // <GPGSID>
        public const string achievement_its_pouring = "CgkI18-M-9keEAIQCQ"; // <GPGSID>

}

